[tool.poetry]
name = "python-course"
version = "0.1.0"
description = "Place holder for all course practive files"
authors = ["Bushan Bengaluru"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
